ALTER TABLE incomes ADD COLUMN IF NOT EXISTS is_recurring BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE incomes ADD COLUMN IF NOT EXISTS recurrence_frequency VARCHAR(20);
ALTER TABLE incomes ADD COLUMN IF NOT EXISTS next_due_date DATE;
ALTER TABLE incomes ADD COLUMN IF NOT EXISTS recurrence_end_date DATE;

ALTER TABLE expenses ADD COLUMN IF NOT EXISTS is_recurring BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS recurrence_frequency VARCHAR(20);
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS next_due_date DATE;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS recurrence_end_date DATE;
